a=prompt("Digite um número");
a=parseInt(a);
b=prompt("Digite um número");
b=parseInt(b);
document.write("soma: "+ (a+b));
document.write("<br> subtração: " + (a-b));
document.write("<br> multiplicação: "+ (a*b));
document.write("<br> Divisão: "+ (a/b));
document.write("<br> Simbolo % Módulo (resto da divisão):  "+ (a%b));
document.write("<br> Simbolo ** Exponenciação:  "+ (a**b));